### ISSUE TITLE
Image zoomed in while changing device orientation

### ISSUE THREAD

**Issue by faheemamjadgeniteam** [mwaterfall/MWPhotoBrowser#398] opened 2015-05-22 11:00 UTC
I am facing some minor issue regarding your library that is when an image is loaded and we change the orientation of device i.e. Portrait to Landscape, while the device is rotating & adjusting its views to the new orientation, the image become bigger than its usual size for a very short period of time then it come back to its original size as soon the animation ended. It gives the user impact that the image is zoomed in before resizing the image to the device orientation. I have recently upgraded the Library to the latest code available on git.

Can you help me int his regard whether its a bug or feature you have added in the the latest code? or Can you help me to remove this feature as this is not giving a good user experience.

**Comment by ips-pablon** [comment] 2015-05-25 18:15
I'm facing the same problem.
I noticed this only happens on iOS 8 devices.
On my scenario, the image remain zoomed and takes the user to a different image in the gallery while rotating.

**Comment by mwaterfall** [comment] 2015-07-06 14:34
I believe this is a dupe of #361 but let me know if you disagree and we can look at reopening this issue.

**Closed by mwaterfall** 2015-07-06 14:34 UTC
